### ISSUE TITLE
HTML Modules

### ISSUE THREAD

**Issue by matthewp** [matthewp/script-type-module#34]
I have a project where I use both this polyfill *and* HTML imports, so I think it's about time we get HTML modules included here.  I'm cc/ing @justinfagnani because he expressed interest in this idea and  @TakayoshiKochi because I noticed he has already been experimenting in a fork.

The only docs I know of about how HTML modules might work [is here](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/HTML-Imports-and-ES-Modules.md).  My initial questions are:

1. What does an HTML module export? From that doc it sounds like it has a single `default` export that is the module's own `document`.
2. Aside from the syntax, do HTML modules differ from Imports in any way?

I'm assuming you should be able to do both:

```html
<script type="module-polyfill" src="./path/to/tabs.html"></script>
```

Which is pretty much exactly equivalent to a `<link rel=import>`. This should also work:

```js
import doc from './path/to/tabs.html';

// Not sure what you would do with the `doc`, if anything
```

**Comment by TakayoshiKochi** [comment]
What I'm doing in the fork is quite experimental and as you pointed out the doc is the only thing available.
Nothing is specified as of now, everything is sketchy.  Probably it's too early to take on HTML modules for this (script-type-module) script.

For the discussion of HTML modules spec, it would be better to do at webcomponents issue tracker, probably not here.  We intend to do that once we have more confidence or concrete proposal (I hope it will be soon<sup>TM</sup>!) but until then any discussion for detailed semantics would go nowhere.

BTW, I appreciate your work for the ES modules polyfill.

**Comment by matthewp** [comment]
Thanks, @TakayoshiKochi, I appreciate your feedback. I think I agree that discussing this more on w3c/webcomponents is probably the way to go, so that's what I'll do for now.  Once a more concrete proposal has surfaced we can revisit experimenting with it here.  I'm going to close this issue for now.

**Comment by matthewp** [comment]
@TakayoshiKochi Is your suggestion that I wait for the concrete proposal from Google before filing issues on w3c/webcomponents, or is it fair game to file issues based on the existing high-level proposal? In particular I'd like to discuss the issue of what an HTML module exports as I think there's some improvement we can do here.

**Comment by TakayoshiKochi** [comment]
@matthewp we don't stop you from doing whatever you want! Any contribution would be precious.
The problem could be, if any, if no one has enough data/experience (as it has never existed!), meaningful discussion might not be done, but in general adding some issue would be beneficial to shape the problem space that HTML module is going to solve.
