### ISSUE TITLE
use `type=module` replace `type=module-polyfill`

### ISSUE THREAD

**Issue by hax** [matthewp/script-type-module#35]
It seems a new attribute `nomodule` has been decided to introduce to the spec, which can be used for feature dectection:

```js
const s = document.createElement('script')
if ('nomodule' in s) {
  // browser support type=module natively
} else {
  // load this polyfill
}
```

**Comment by domenic** [comment]
No, please do not use type=module. See previous discussion at https://github.com/matthewp/script-type-module/issues/21.

**Comment by hax** [comment]
Ok. Let's wait for two stable implementations. (maybe this summer?)

**Comment by matthewp** [comment]
Sorry I missed this, apparently you have to watch your own repos to get notifications.

We won't be changing to type=module, probably ever. As this project is primarily aimed at development use, I don't see a future for it once type=module starts shipping. Personally, I'll be using the built in loader then.
